### ISSUE TITLE
Bound Sword defaults to left hand

### ISSUE THREAD

**Issue by frstwlf** [pWn3d1337/Skyrim_SpellHotbar2#14]
I've tried many things but no matter what I do, Bound Sword always ends up in my left hand when cast from the hotkey. I've even created a new spell in xEdit by duplicating Bound Sword to my own mod (didn't overwrite the vanilla spell) and set it to right hand. 

Whether I have spells or weapons or nothing at all equipped (in either or both hands), the spell I made works when cast from the hotkey as long as I am in the sheathed state. However, the vanilla Bound Sword always ends up equipped in my left hand.

If my hands are up (with or without anything equipped in either), casting my spell from the hotkey equips the vanilla Bound Sword spell to my left hand first without actually casting, then to my right hand (still no cast) and once both hands have Bound Sword equipped, my spell works as intended form the hotkey (i.e. casting Bound Sword in my right hand).

I'm sorry if I effed up anything on my end or if this is known already but I didn't see it in the known issues. Maybe adding an option to select a behavior for bound spells? Thanks for the mod, works great otherwise!
[SpellHotbar2.log](https://github.com/user-attachments/files/17792616/SpellHotbar2.log)

**Comment by pWn3d1337** [comment]
You can set a spell to a specific hand by pressing the button multiple times while in the bind menu. You should see a L, R or D (if dual casting is possible). When no letter is shown it will default to left hand in most cases.
