### ISSUE TITLE
Trying to cast summons from too far away has unintended side effects

### ISSUE THREAD

**Issue by LoftedAphid86** [pWn3d1337/Skyrim_SpellHotbar2#7]
If you attempt summon something at a distance where the spell would fail, the spell doesn't complete meaning the cost isn't refunded, magicka doesn't regenerate, and other hotbar spells can't be cast until you attempt to cast a spell normally

**Comment by pWn3d1337** [comment]
The mana loss on range fail is known and I'm unsure if I'm able to fix this, but the other problems should not happen, I will look into this.

**Comment by pWn3d1337** [comment]
Confirmed the bug, the game seems to let the cast stuck in that case.

**Comment by pWn3d1337** [comment]
I found a very promising solution, directly after casting a spell can be checked for PlayerCharacter->isCasting(spell). This is false in case of a succesful cast but true in case of a "stuck" spell. So non-concentration spells with target location will get this check and on fail no magicka will be removed.
